from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from munk.adapters.local_api.app import create_local_api_app

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_PATH = PROJECT_ROOT / "munk-loop" / "docs" / "munk-ai" / "local-api.loop.json"

# Munk Loop Phase 0–2 integration surface. Keep in sync with munk-loop/docs/munk-ai-integration.md
LOOP_API_PATHS: tuple[str, ...] = (
    "/v1/devices",
    "/v1/review",
    "/v1/verify/change",
    "/v1/runs/{operation_id}",
    "/v1/runs/{operation_id}/artifacts",
    "/v1/runs/{operation_id}/artifacts/{artifact_id}/content",
    "/v1/runs/{operation_id}/cancel",
)


def _serialize_openapi() -> dict[str, Any]:
    app = create_local_api_app(start_recording_bridge=False)
    schema = app.openapi()
    if not isinstance(schema, dict):
        raise TypeError("expected OpenAPI schema dict from app.openapi()")
    return schema


def _iter_refs(value: Any) -> Iterable[str]:
    if isinstance(value, dict):
        ref = value.get("$ref")
        if isinstance(ref, str):
            yield ref
        for nested in value.values():
            yield from _iter_refs(nested)
    elif isinstance(value, list):
        for item in value:
            yield from _iter_refs(item)


def _parse_component_ref(ref: str) -> tuple[str, str] | None:
    if not ref.startswith("#/components/"):
        return None
    parts = ref[len("#/components/") :].split("/", 1)
    if len(parts) != 2:
        return None
    section, name = parts
    if not section or not name:
        return None
    return section, name


def _collect_component_ref_closure(full_schema: dict[str, Any], seed_refs: set[str]) -> set[str]:
    components = full_schema.get("components")
    if not isinstance(components, dict):
        return set()

    collected: set[str] = set()
    pending = set(seed_refs)

    while pending:
        ref = pending.pop()
        if ref in collected or not ref.startswith("#/components/"):
            continue
        collected.add(ref)

        parsed = _parse_component_ref(ref)
        if parsed is None:
            continue
        section, name = parsed
        section_values = components.get(section)
        if not isinstance(section_values, dict):
            continue
        component = section_values.get(name)
        if component is None:
            continue
        for nested_ref in _iter_refs(component):
            if nested_ref.startswith("#/components/") and nested_ref not in collected:
                pending.add(nested_ref)

    return collected


def _prune_openapi(full_schema: dict[str, Any], allowed_paths: tuple[str, ...]) -> dict[str, Any]:
    paths = full_schema.get("paths")
    if not isinstance(paths, dict):
        raise ValueError("OpenAPI schema missing paths")

    missing_paths = [path for path in allowed_paths if path not in paths]
    if missing_paths:
        missing = ", ".join(missing_paths)
        raise ValueError(f"allowed Loop paths not found in OpenAPI schema: {missing}")

    filtered_paths = {path: paths[path] for path in allowed_paths}

    seed_refs = set(_iter_refs(filtered_paths))
    component_refs = _collect_component_ref_closure(full_schema, seed_refs)

    full_components = full_schema.get("components")
    if not isinstance(full_components, dict):
        full_components = {}

    pruned_components: dict[str, Any] = {}
    for ref in sorted(component_refs):
        parsed = _parse_component_ref(ref)
        if parsed is None:
            continue
        section, name = parsed
        section_values = full_components.get(section)
        if not isinstance(section_values, dict) or name not in section_values:
            continue
        pruned_components.setdefault(section, {})[name] = section_values[name]

    info = dict(full_schema.get("info", {}))
    description = info.get("description")
    suffix = (
        "Trimmed OpenAPI subset for Munk Loop (verify/review/runs/devices). "
        "Generated by scripts/generate_loop_local_api_openapi.py."
    )
    info["description"] = f"{description}\n\n{suffix}" if description else suffix

    pruned: dict[str, Any] = {
        "openapi": full_schema.get("openapi"),
        "info": info,
        "paths": filtered_paths,
        "components": pruned_components,
        "x-munk-loop-subset": True,
        "x-munk-loop-paths": list(allowed_paths),
    }

    for key in ("servers", "tags", "security"):
        if key in full_schema:
            pruned[key] = full_schema[key]

    return pruned


def _render_schema(schema: dict[str, Any]) -> str:
    return json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def _write_schema(output_path: Path, content: str) -> int:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def _check_schema(output_path: Path, content: str) -> int:
    if not output_path.exists():
        print(f"missing generated schema: {output_path}", file=sys.stderr)
        return 1
    current = output_path.read_text(encoding="utf-8")
    if current != content:
        print(f"outdated generated schema: {output_path}", file=sys.stderr)
        return 1
    print(f"schema is up to date: {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the trimmed Local API OpenAPI schema for Munk Loop.",
    )
    parser.add_argument("mode", choices=("write", "check"))
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Path to the generated Loop OpenAPI JSON file.",
    )
    args = parser.parse_args()

    content = _render_schema(_prune_openapi(_serialize_openapi(), LOOP_API_PATHS))
    if args.mode == "write":
        return _write_schema(args.output, content)
    return _check_schema(args.output, content)


if __name__ == "__main__":
    raise SystemExit(main())
