from __future__ import annotations

from munk.core.action_target_building import (
    build_action_targets,
    build_canonical_target_parts,
    build_target_parts,
    select_form_first_tree_targets,
)
from munk.core.action_target_fingerprint import handle_fingerprint
from munk.core.action_target_models import (
    TREE_PART_MAX,
    VISION_PART_MAX,
    ActionTarget,
    ActionTargetResolution,
    TargetHandle,
    TargetParts,
)
from munk.core.action_target_refs import (
    build_dom_handle,
    build_spatial_handle,
    handle_as_mapping,
    is_text_input_handle,
    is_text_input_target,
    normalize_target_ref,
    parse_target_ref,
    requires_set_value_action,
    requires_set_value_handle,
    set_value_control_family,
)
from munk.core.action_target_resolution import (
    build_recording_action_summary,
    degrade_target_confidence,
    find_action_target_by_box,
    find_action_targets_by_stable_key,
    find_focused_or_input_target,
    rank_targets_by_point,
    resolve_action_target,
    resolve_recording_action_targets,
    summarize_action_target,
)
from munk.core.action_target_text import (
    DEFAULT_TARGET_PART_LIMIT,
    MATCH_TARGET_LIMIT,
    MAX_TARGET_PART_LIMIT,
    TargetListSource,
    TargetMatchTextResult,
    TargetTextWindowStats,
    build_target_detail_text,
    build_targets_list_text,
    build_targets_match_text,
    build_targets_text,
    clamp_target_part_limit,
    count_targets_in_text,
    default_tree_seed_limit,
    measure_targets_list_window,
    measure_targets_seed_window,
)

__all__ = [
    "DEFAULT_TARGET_PART_LIMIT",
    "MATCH_TARGET_LIMIT",
    "MAX_TARGET_PART_LIMIT",
    "TREE_PART_MAX",
    "VISION_PART_MAX",
    "ActionTarget",
    "ActionTargetResolution",
    "TargetHandle",
    "TargetListSource",
    "TargetMatchTextResult",
    "TargetParts",
    "TargetTextWindowStats",
    "build_action_targets",
    "build_canonical_target_parts",
    "build_dom_handle",
    "build_recording_action_summary",
    "build_spatial_handle",
    "build_target_detail_text",
    "build_target_parts",
    "build_targets_list_text",
    "build_targets_match_text",
    "build_targets_text",
    "clamp_target_part_limit",
    "count_targets_in_text",
    "default_tree_seed_limit",
    "degrade_target_confidence",
    "find_action_target_by_box",
    "find_action_targets_by_stable_key",
    "find_focused_or_input_target",
    "handle_as_mapping",
    "handle_fingerprint",
    "is_text_input_handle",
    "is_text_input_target",
    "measure_targets_list_window",
    "measure_targets_seed_window",
    "normalize_target_ref",
    "parse_target_ref",
    "rank_targets_by_point",
    "requires_set_value_action",
    "requires_set_value_handle",
    "resolve_action_target",
    "resolve_recording_action_targets",
    "select_form_first_tree_targets",
    "set_value_control_family",
    "summarize_action_target",
]
